---
title: "Exhibition D: Art Around the World"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
---

```{r setup, include=FALSE, echo=FALSE}
library(flexdashboard)
library(tidyverse)
library(plotly)
library(shiny)
library(sf)
library(rnaturalearth)
library(rsconnect)
```


```{r, echo=FALSE, warning=FALSE}
load("data/met.RData")
```

```{r, echo=FALSE}
met_country <- met |> 
mutate(country = case_when(
    country == "Central Turkey" ~ "Turkey",
    country == "USA" ~ "United States", 
    country == "Iran(Persia)" ~ "Iran", 
    country == "Ivory Coast" ~ "Cote d'Ivoire", 
    country == "iran" ~ "Iran", 
    country == "Eastern India" ~ "India",
    country == "Byzantine Egypt" ~ "Egypt",
    country == "Western Australia" ~ "Australia",
    country == "England" ~ "United Kingdom",
    country == "England|England" ~ "United Kingdom",
    country == "Crotia(former Yugoslavia)" ~"Crotia",
    country == "Western France" ~ "France", 
    country == "Southern Netherlands" ~ "Netherlands",
    country == "Southern Netherland" ~ "Netherlands", 
    country == "Scotland" ~ "United Kingdom",
    country == "Republic of Congo" ~ "Congo", 
    country == "Republic of Cameroon" ~ "Cameroon",
    country == "Republic of Costa Rica" ~ "Costa Rica",
    country == "Republic of Guinea-Bissau" ~ "Guinea-Bissau",
    country == "Republic of the Marshall Islands" ~ "Marshall Isl",
    country == "Republic of Guinea-Bissau" ~ "Guinea-Bissau",
    country == "Republic of Benin" ~ "Benin",
    country == "Northern Iran"  ~"Iran",
    country == "Northwestern Iran"  ~"Iran",
    country == "Northwest Iran"  ~"Iran",
    country == "Northwestern Iran" ~"Iran",
    country == "Northern India" ~ "India",
    country == "Nothern France" ~ "France", 
    TRUE ~ as.character(country)
  ), 
  country = str_replace(country, "present-day ", ""))

```

```{r, echo=FALSE, message=FALSE}
object_counts <- met_country |> 
  group_by(country, object_name) |> 
  summarise(n_objects = n()) |> 
  group_by(country) |> 
  summarise(total_objects = sum(n_objects, na.rm = TRUE)) 

world <- ne_countries(scale = "medium", returnclass = "sf")

world <- left_join(world, object_counts, by = c("name" = "country"))
world2 <- left_join(object_counts, world, by = c("country" = "name"))

world2 <- world2 |> 
  filter(is.na(scalerank))
```

Column {.sidebar}
-----------------------------------------------------------------------

```{r, echo=FALSE}
country_vec = world |>  pull(name) |> unique()

selectInput(
  inputId = "Country", 
  label = h3("Select Country"),
  choices = country_vec)

```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r, echo=FALSE}
# Shiny Server
renderPlotly({
    # light grey boundaries
    l <- list(color = toRGB("grey"), width = 0.5)

    g <- list(
      showframe = FALSE,
      showcoastlines = FALSE,
      projection = list(type = 'mercator')
    )

    selected_country <- input$Country
    filtered_world <- world  |> 
      filter(name == selected_country)

    world |> 
      plot_geo() |> 
      add_trace(
        z = ~total_objects, color = ~total_objects, colors = 'Blues',
        text = ~name, locations = ~su_a3, marker = list(line = l)
      ) %>%
      colorbar(title = 'Number of Objects by Country', len = 0.3) |> 
      layout(
        title = "Number of Objects by Country",
        geo = g,
        height = "150vh"
      ) %>%
      add_trace(
        data = filtered_world,
        type = 'scattergeo',
        mode = 'markers',
        marker = list(color = 'pink', size = 30),
        text = ~name,
        hoverinfo = 'text'
      )
  })


```

### Description

The country with most of object is Egypt. 

\ \par
T

\ \par
  * 
  
\ \par


Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r, echo=FALSE}

ui <- fluidPage(
  titlePanel("Number of Objects by Country"),
  mainPanel(
    plotlyOutput("objectPlot")
  )
)

server <- function(input, output) {
  output$objectPlot <- renderPlotly({
    world2 |> 
      group_by(country, total_objects.x) |> 
      summarise(n = n()) |> 
      arrange(desc(total_objects.x)) |> 
      plot_ly(
        x = ~country,
        y = ~total_objects.x,
        type = 'bar',
        text = ~country,
        marker = list(color = 'skyblue')
      ) |> 
      layout(
        title = "Number of Objects Without A Certain Country",
        xaxis = list(title = "Country"),
        yaxis = list(title = "Total Objects"),
        hovermode = 'closest'
      )
  })
}

# Run the Shiny app
shinyApp(ui, server)


```


### Chart C

```{r, echo=FALSE}

# UI ----
ui <- fluidPage(
  titlePanel("Top 20 Countries by Number of Objects"),

  # Main layout with output definition ----
  mainPanel(
    plotlyOutput("top_countries_chart")
  )
)

# Server ----
server <- function(input, output) {
  
  output$top_countries_chart <- renderPlotly({
    top_countries <- object_counts %>%
      arrange(desc(total_objects)) %>%
      head(20)

    plot_ly(data = top_countries, x = ~country, y = ~total_objects, type = "bar") %>%
      layout(
        title = "Top 20 Countries by Number of Objects",
        xaxis = list(title = "Country", categoryorder = "total ascending"),
        yaxis = list(title = "Number of Objects")
      )
  })
}

# Run the application 
shinyApp(ui, server)

```

