---
title: "Final Project - Deliverable 1 - Due Nov 10, 2023"
author: "Jennifer Osei, Melike Aksoy, Emily Murphy, Aleya Khalifa, Andy Turner"
date: "2023-11-06"
output: github_document
---
##########################################################################
### Deliverable 1 - Project Topic Proposal 
##########################################################################

#### Deliverables (General)
#### Submissions

Other than peer assessments, each deliverable will appear online (as e.g. a GH repo or youtube video). Links should be submitted via Courseworks by one team member (not necessarily the same person for each deliverable).

#### Team registration and proposal
First, you will define your teams and propose a project. 
This proposal should be a half-page to a page in length and include:

1. The group members (names and UNIs)

```{r, echo = FALSE, message = FALSE}

library(tidyverse)

our_team = tibble (Group_Members = c("Jennifer Osei", "Melike Aksoy","Emily Murphy", "Aleya Khalifa", "Andy Turner"), 
                UNIs = c("jao2195", "mma2277", "erm2195", "ak4598", "ajt2206"))

knitr::kable(our_team, caption = "Table 1: P8015 Data Science Final Project Team Members and Their UNIs ", align = "ll")

```


2. The tentative project title
3. The motivation for this project
4. The intended final products
5. The anticipated data sources
6. The planned analyses / visualizations / coding challenges
7. The planned timeline


There should be one proposal per group, written collaboratively using .Rmd (rendering to a GH document) in a dedicated GitHub repo. This is intended to describe a project that is in the planning stages. Only one team member should submit this proposal via Canvas.

Please also submit (only once per team) a list of your team’s UNIs using this form. Doing so will help us keep track of teams.[Completed Mon. November 6, 2023 JO]

