---
title: "Welcome to The Art of Data Science: The Met Museum"
output: 
  html_document:
    toc: true
    toc_float: true
    theme: cosmo
---

<html lang="en">

<head>
    <link rel="stylesheet" href="style.css">
    <title> </title>

  <style type="text/css">
  body {
    color: white;  /* Set the font color to white */
    font-weight: bold;  /* Make the text bold */
  }
  </style>

</head>

  <body>
   <h1></h1> 
  </body>


</html>
<style type="text/css">
  body {
    font-family: 'sans_serif', sans-serif; /* Specify the desired font family */
  }
  
<style type="text/css">
  
  body {
    font-size: 10pt;
    color: white;  
    font-weight: bold;  
  }
  
  .highlight {
            background-color: rgba(0, 0, 0, 0.6);  
            padding: 5px; /* Adjust the padding as needed */
  }
  
</style>

<center> <h1 class="highlight"> <font size="10"> <b> Welcome to The Art of Data Science: <br> The Met Museum </h1 class="highlight"> </font> 

<center><h1 class="highlight"> <font size="10"> <b> Project Met'ivation </font> </h1 class="highlight"> <p> Check out why we chose to do this project here! </p> </center>

<center><h1 class="highlight"> <font size="10"> <b> Exhibits </font> </h1 class="highlight"> <p> Check out our exciting Met Data in Exhibit A ! <br> Check out our exciting Met Data in Exhibit B ! <br> Check out our exciting Met Data in Exhibit C !Check out our exciting Met Data in Exhibit D !  </p> </center>

<center><h1 class="highlight"> <font size="10"> <b> Project Report </font> </h1 class="highlight"> <p> Check out the Summary of our works in Project Report! </p> </center>

<center><h1 class="highlight"> <font size="10"> <b> Meet the Curators </font> </h1 class="highlight"> <p> Check out our amazingly creative data team who made this project possible! </p> </center>

<center><h1 class="highlight"> <font size="10"> <b> We hope you enjoy your virtual visit to The Art of Data Science: The Met Museum! Come and Visit Us Again!  </font> </h1 class="highlight">  </center>

